spring:

  #DATABASE H2
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    driver-class-name: org.h2.Driver
  #    username: db_user
  #    password: db_password
  #
  #  jpa:
  #    database-platform: org.hibernate.dialect.H2Dialect
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #
  #  h2:
  #  console:
  #    enabled: true
  #    path: /h2-console

  #DATABASE PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Pode ser alterado para 'validate', 'create', 'create-drop' conforme necessário
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true   # Mostra as queries no console
        format_sql: true # Formata as queries no console
  sql:
    init:
      mode: always # Garante que scripts SQL de inicialização sejam executados

logging:
  level:
    org.springframework.security: DEBUG